### ISSUE TITLE
request for the origin of the data

### ISSUE THREAD

**Issue by luckyorange-liu** [jnederlo/dfs_optimizers#5]
@jnederlo Hello jnederlo, I also do a similar work on the picking winner problem in the application of daily fantasy sport with considering correlation. Could  I consult to about the origin of your example input,  such as the year and the website. Thank you very much!

**Comment by jnederlo** [comment]
@luckyorange-liu the example input was data collected by me from many different sources and put into a custom database. I then made my own projections and saved the results to a file. 

So there isn't a single source to get it from. One place you might consider looking for data could be:

MySportsFeeds.com: Live Sports Data Feed APIwww.mysportsfeeds.com

I used them in the past as one of my data sources and they've increased their offerings since.

**Comment by luckyorange-liu** [comment]
Thanks a lot, jnederlo.
